version: "3"
services:

  mongo:
    image: mongo
    ports:
        - "2001:27017"

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4001:5000"
    links:
      - mongo
    environment:
      - "MONGO=mongodb://mongo/7in14"